server:
  port: 8800
  db_path: "./build-server.db"
  refresh_concurrency: 4
  # base_path: /build-server

repositories:
  - name: example-repo
    path: /path/to/example-repo
    remote: origin
    default_branch: main
    make_target: deploy
